INSERT INTO public."Region" VALUES (3525, 212, N'Krym');
INSERT INTO public."Region" VALUES (3526, 212, N'Odes''ka Oblast''');
INSERT INTO public."Region" VALUES (3527, 212, N'Kharkivs''ka Oblast''');
INSERT INTO public."Region" VALUES (3528, 212, N'Poltavs''ka Oblast''');
INSERT INTO public."Region" VALUES (3529, 212, N'Kyyivs''ka Oblast''');
INSERT INTO public."Region" VALUES (3530, 212, N'Zakarpats''ka Oblast''');
INSERT INTO public."Region" VALUES (3531, 212, N'Sums''ka Oblast''');
INSERT INTO public."Region" VALUES (3532, 212, N'Donets''ka Oblast''');
INSERT INTO public."Region" VALUES (3533, 212, N'Khersons''ka Oblast''');
INSERT INTO public."Region" VALUES (3534, 212, N'L''vivs''ka Oblast''');
INSERT INTO public."Region" VALUES (3535, 212, N'Cherkas''ka Oblast''');
INSERT INTO public."Region" VALUES (3536, 212, N'Vinnyts''ka Oblast''');
INSERT INTO public."Region" VALUES (3537, 212, N'Rivnens''ka Oblast''');
INSERT INTO public."Region" VALUES (3538, 212, N'Khmel''nyts''ka Oblast''');
INSERT INTO public."Region" VALUES (3539, 212, N'Chernihivs''ka Oblast''');
INSERT INTO public."Region" VALUES (3540, 212, N'Dnipropetrovs''ka Oblast''');
INSERT INTO public."Region" VALUES (3541, 212, N'Mykolayivs''ka Oblast''');
INSERT INTO public."Region" VALUES (3542, 212, N'Ternopil''s''ka Oblast''');
INSERT INTO public."Region" VALUES (3543, 212, N'Zhytomyrs''ka Oblast''');
INSERT INTO public."Region" VALUES (3544, 212, N'Chernivets''ka Oblast''');
INSERT INTO public."Region" VALUES (3545, 212, N'Luhans''ka Oblast''');
INSERT INTO public."Region" VALUES (3546, 212, N'Sevastopol''');
INSERT INTO public."Region" VALUES (3547, 212, N'Kirovohrads''ka Oblast''');
INSERT INTO public."Region" VALUES (3548, 212, N'Ivano-Frankivs''ka Oblast''');
INSERT INTO public."Region" VALUES (3549, 212, N'Zaporiz''ka Oblast''');
INSERT INTO public."Region" VALUES (3550, 212, N'Volyns''ka Oblast''');