INSERT INTO public."Region" VALUES (3525, N'Krym', 212);
INSERT INTO public."Region" VALUES (3526, N'Odes''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3527, N'Kharkivs''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3528, N'Poltavs''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3529, N'Kyyivs''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3530, N'Zakarpats''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3531, N'Sums''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3532, N'Donets''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3533, N'Khersons''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3534, N'L''vivs''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3535, N'Cherkas''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3536, N'Vinnyts''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3537, N'Rivnens''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3538, N'Khmel''nyts''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3539, N'Chernihivs''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3540, N'Dnipropetrovs''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3541, N'Mykolayivs''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3542, N'Ternopil''s''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3543, N'Zhytomyrs''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3544, N'Chernivets''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3545, N'Luhans''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3546, N'Sevastopol''', 212);
INSERT INTO public."Region" VALUES (3547, N'Kirovohrads''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3548, N'Ivano-Frankivs''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3549, N'Zaporiz''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3550, N'Volyns''ka Oblast''', 212);
INSERT INTO public."Region" VALUES (3551, N'', 212);